### ISSUE TITLE
ImportError: No module named caffe

### ISSUE THREAD

**Issue by jasaldivara** [carl-codling/LucidGTK#2]
I have Caffe compiled and installed

When I run ´lucid-gtk´ on the terminal, it says there in no caffe module, and doesn't start:

```
Traceback (most recent call last):
  File "/usr/local/bin/lucid-gtk", line 6, in <module>
    from lucidgtk.dream import DreamWindow
  File "/usr/local/lib/python2.7/site-packages/lucidgtk/dream.py", line 26, in <module>
    import caffe
ImportError: No module named caffe
```

I'm on Fedora 22 x86_64

**Comment by carl-codling** [comment]
Try copying the caffe/python/caffe folder to the python2.7/dist-packages folder:

sudo cp -a /home/MyUserName/caffe/python/caffe /usr/local/lib/python2.7/dist-packages

I think this more an issue with caffe, I had the same issue setting it up on Ubuntu 14.04 but followed the process outlined here including the additional comment from user skatardude10 
https://www.reddit.com/r/deepdream/comments/3cd1yf/howto_install_on_ubuntulinux_mint_including_cuda/
