### ISSUE TITLE
CONFIGURATION ERROR: Please set the locations for deepdream images and videos to be stored

### ISSUE THREAD

**Issue by jasaldivara** [carl-codling/LucidGTK#3]
When I run lucid-gtk from the command line, I get this message from a Lucid-GTK window:

```
CONFIGURATION ERROR: Please set the locations for deepdream images and videos to be stored
```

I don't know how to set that locations
When I close this error message window, the main Lucid-GTK window also closes.

**Comment by carl-codling** [comment]
Hmmm, which version are you using, 0.1.0 or 0.1.1? If that message pops up then the settings window should also appear (in which you can set the locations)... I should have a new release out either tonight or tomorrow with lots of fixes, sorry to hear you're having issues getting this set up though.

One way you could resolve that error is to manually add the paths to the folders by using dconf-editor which is a GUI for editing gsettings objects. You will find the lucid-gtk object in the left menu under org > rebelweb > dreamer and the 2 path settings are 'im-dir' and 'vid-dir'. Enter a valid path to a directory for each and the error should go

**Comment by jasaldivara** [comment]
I'm using version 0.1, downloaded from: http://rebelweb.co.uk/lucid-gtk/

Another problem I found, is that I need to run lucid-gtk from the bvlc_googlenet model folder in order to make lucid-gtk able to find the googlenet model.

**Comment by jasaldivara** [comment]
I'm seeing that both download links from http://rebelweb.co.uk/lucid-gtk/ points to the same 0.1 version file.

**Comment by carl-codling** [comment]
OK, I've just fixed that... 0.1.2 will be there in half an hour or so

**Comment by carl-codling** [comment]
OK, 0.1.2 is there now and I just did a full fresh install with it and everything went well. Let me know how it goes

**Comment by jasaldivara** [comment]
I have installed 0.1.2, and it doesn't work.
This is the output from command line:

```
/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Traceback (most recent call last):
  File "/usr/local/bin/lucid-gtk", line 11, in <module>
    dw.run()
  File "/usr/local/lib/python2.7/site-packages/lucidgtk/dream.py", line 78, in run
    if self.initcaffe() is False:
  File "/usr/local/lib/python2.7/site-packages/lucidgtk/dream.py", line 200, in initcaffe
    text_format.Merge(open(net_fn).read(), model)
IOError: [Errno 2] No existe el fichero o el directorio: ''
```

I'm on Fedora 22 x86_64

**Comment by carl-codling** [comment]
Ahhh, OK I've just managed to duplicate this error, I wasn't seeing it because my gsettings were being saved from the previous install. It's a matter of setting the caffe paths in the gsettings object which can be done with dconf-editor.

'model-file' and 'deploy-prototxt' are the 2 settings that need to be set
ie. /home/USERNAME/caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel
and /home/USERNAME/caffe/models/bvlc_googlenet/deploy.prototxt

**Comment by carl-codling** [comment]
And I'll get that fixed asap

**Comment by carl-codling** [comment]
Hey, just wondering if this worked for you and I can close the issue? Cheers.
